import { StyleSheet } from 'react-native';

// Paleta alinhada ao painel web (visual escuro premium).
export const colors = {
  bg: '#080b16',
  panel: '#121830',
  panel2: '#1b2340',
  text: '#eef1fb',
  muted: '#98a3c4',
  accent: '#34d399',
  accent2: '#60a5fa',
  danger: '#f87171',
  border: '#232c4d',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg, padding: 16 },
  title: { color: colors.text, fontSize: 24, fontWeight: '800', marginBottom: 12 },
  subtitle: { color: colors.muted, fontSize: 14, marginBottom: 16 },
  input: {
    backgroundColor: colors.panel2,
    color: colors.text,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    marginBottom: 12,
  },
  button: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  buttonText: { color: '#04231a', fontWeight: '800', fontSize: 17 },
  secondaryButton: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryText: { color: colors.text, fontWeight: '700', fontSize: 16 },
  courtesyButton: {
    backgroundColor: colors.panel2,
    borderColor: colors.accent2,
    borderWidth: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  courtesyText: { color: colors.accent2, fontWeight: '800', fontSize: 16 },
  error: { color: colors.danger, marginTop: 8 },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  productTile: {
    flex: 1,
    minHeight: 92,
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 15,
    margin: 6,
    padding: 13,
    justifyContent: 'center',
  },
  productName: { color: colors.text, fontSize: 16, fontWeight: '700' },
  productPrice: { color: colors.accent, fontSize: 15, marginTop: 4, fontWeight: '700' },
  statusBar: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  qtyBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  qtyBadgeText: { color: '#05122b', fontWeight: '800', fontSize: 13 },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
  },
  cartName: { color: colors.text, fontSize: 15, fontWeight: '700' },
  cartSub: { color: colors.muted, fontSize: 12, marginTop: 2 },
  stepBtn: {
    width: 38,
    height: 38,
    borderRadius: 9,
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepQty: { minWidth: 34, alignItems: 'center', justifyContent: 'center' },
  stepText: { color: colors.text, fontSize: 18, fontWeight: '800' },
  removeBtn: {
    width: 38,
    height: 38,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeText: { color: colors.danger, fontSize: 16, fontWeight: '800' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2,4,11,0.66)',
    justifyContent: 'center',
    padding: 22,
  },
  modalCard: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
  },
  pill: {
    color: colors.muted,
    fontSize: 13,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
