import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#0b1020',
  panel: '#151b30',
  panel2: '#1e2742',
  text: '#e8ecf6',
  muted: '#93a0bf',
  accent: '#34d399',
  accent2: '#60a5fa',
  danger: '#f87171',
  border: '#2a3454',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg, padding: 16 },
  title: { color: colors.text, fontSize: 24, fontWeight: '800', marginBottom: 12 },
  subtitle: { color: colors.muted, fontSize: 14, marginBottom: 16 },
  input: {
    backgroundColor: colors.panel2,
    color: colors.text,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 14,
    fontSize: 16,
    marginBottom: 12,
  },
  button: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  buttonText: { color: '#04231a', fontWeight: '800', fontSize: 17 },
  secondaryButton: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryText: { color: colors.text, fontWeight: '700', fontSize: 16 },
  error: { color: colors.danger, marginTop: 8 },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  productTile: {
    flex: 1,
    minHeight: 88,
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    margin: 6,
    padding: 12,
    justifyContent: 'center',
  },
  productName: { color: colors.text, fontSize: 16, fontWeight: '700' },
  productPrice: { color: colors.accent, fontSize: 15, marginTop: 4 },
  statusBar: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  pill: {
    color: colors.muted,
    fontSize: 13,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
